<template name="DashboardTransferFundsToTreasuryStory">
  <div class="dashboard-story">
    <header class="header">
      <img class="close-btn" src="@/assets/icon/close_big.svg" alt="close" />
      <img class="image" src="@/assets/images/euro-coin.svg" alt="story" />
    </header>
    <main class="main">
      <h1 class="title">Transfer funds to treasury and earn passive income.</h1>
      <p class="description">
        Using treasure, you can provide liquidity to the platform.
      </p>
      <p class="description">
        In return you will be rewarded with fees generated by users on that
        platform.
      </p>
      <img class="image" src="@/assets/images/safe.png" alt="safe" />
    </main>
    <footer class="footer">
      <button class="btn">Add Liquidity</button>
    </footer>
  </div>
</template>

<script setup lang="ts">
</script>

<style lang="scss">
.dashboard-story {
  height: 100%;
  padding: 32px 24px;

  background: linear-gradient(180deg, #fff9e6 0%, rgba(255, 249, 230, 0) 20%);

  > .header {
    display: flex;
    flex-direction: column;
    margin-bottom: 16px;

    > .close-btn {
      height: 24px;
      width: 24px;
      margin-bottom: 15px;
    }

    > .image {
      height: 45px;
      width: 45px;
    }
  }

  > .main {
    > .title {
      font-weight: 800;
      font-size: 28px;
      line-height: 34px;
      letter-spacing: 0.0038em;
      margin-bottom: 16px;
    }

    > .description {
      font-size: 17px;
      line-height: 22px;
      letter-spacing: -0.0043em;
      margin-bottom: 32px;
    }

    > .image {
      padding-left: 20%;
      margin-bottom: 62px;
    }
  }

  > .footer {
    > .btn {
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      width: 343px;
      height: 48px;
      left: 16px;
      top: 710px;
      background: $color-primary;
      border-radius: 13px;
      color: $color-white;
      font-weight: 600;
      font-size: 17px;
      line-height: 22px;
    }
  }
}
</style>