name: tests
on:
  push:
    branches:
      - 'feature/#387yn1r'

jobs:
  call-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Run autotests from liber-app-autotests
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/cryptowize-tech/liber-app-autotests/actions/workflows/autotest.yml/dispatches \
          -d '{"ref":"main","inputs":{"baseApiUrl":"https://api.dev.liber.casa/"}}'
#      - uses: actions/github-script@v6
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          script: |
#            await github.rest.actions.createWorkflowDispatch({
#              owner: context.repo.owner,
#              repo: 'liber-app-autotests',
#              workflow_id: 'autotest.yml',
#              ref: 'develop'
#            })