name: tests
on:
  push:
    branches:
      - 'feature/#387yn1r'

jobs:
  call-workflow:
    runs-on: self-hosted
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'liber-app-autotests',
              workflow_id: 'autotest.yml',
              ref: 'main'
            })